### ISSUE TITLE
I want jar

### ISSUE THREAD

**Issue by GabBiswajit** [DavyCraft648/Barrel#10]
Idk how i convert this into a jar and also I don't have this egg for my Pterodactyl® panel can provide me both off tham ??

It's my request because i want to test this proxy from a long!

**Comment by Azvyl** [comment]
You should be able to download the resulting jar via [GitHub actions](https://github.com/DavyCraft648/Barrel/actions)

For the pterodactyl egg, I don't really understand because I didn't use pterodactyl panel

**Comment by GabBiswajit** [comment]
What pterodactyl panel need to run Minecraft server when you run your server in which game panel ??
